### PR TITLE
WMDP-26 Set Up PR Template

### PR DESCRIPTION
**Pull request by aplybeah**
## Changes
* added a `.github` folder which should store all github related processes (e.g. github actions, and templates)
* added PR template
GitHub docs on the subject [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
## Testing
New PRs should look like this after this change is added: 
image

### CODE REVIEW

**Comment by aplybeah** [comment]
This PR has been approved here: https://github.com/navapbc/wic-mt-demo-project-eligibility-screener/pull/1
Gentle nudge since I can't merge this myself. cc: @rocketnova

**Review by rocketnova — DISMISSED** [review]
LGTM!

**Review by rocketnova — COMMENTED** [review]
@aplybeah Actually, could we rename this file to lowercase `pull_request_template.md` to align with what the [Github docs](https://docs.github.com/en/enterprise-cloud@latest/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) use?

**Review by rocketnova — APPROVED** [review]
Thank you!

**Pull request merged**
